### ISSUE TITLE
3D coinage

### ISSUE THREAD

**Issue by bd-ongithub** [turtlecoin/brand#1]
Some renders and a working flat backed STL for printing.

![hex_trtl-1](https://user-images.githubusercontent.com/35929209/35823075-4d401678-0a7c-11e8-8d9a-3c341f84ccf7.png)
![trtl_3](https://user-images.githubusercontent.com/35929209/35823076-4d546aa6-0a7c-11e8-9063-edc3ec7231cd.png)
![trtl_2](https://user-images.githubusercontent.com/35929209/35823077-4d757912-0a7c-11e8-963a-fc74358d5934.png)
![trtl_](https://user-images.githubusercontent.com/35929209/35823078-4d884cb8-0a7c-11e8-8d13-9037bd31f05c.png)
![trtl2](https://user-images.githubusercontent.com/35929209/35823079-4d95c5be-0a7c-11e8-9ce8-f56478563afa.png)
![trtl](https://user-images.githubusercontent.com/35929209/35823081-4da97852-0a7c-11e8-931a-8f08b5526d97.jpg)
![hex_trtl-3](https://user-images.githubusercontent.com/35929209/35823082-4db9db5c-0a7c-11e8-8652-0414bbef8e34.png)
![hex_trtl-2](https://user-images.githubusercontent.com/35929209/35823083-4dd2cea0-0a7c-11e8-8718-09a2008881c2.png)

[TRTL Coin _ 3D print _ flat back.zip](https://github.com/turtlecoin/brand/files/1696390/TRTL.Coin._.3D.print._.flat.back.zip)

**Comment by CamHardy** [comment]
Pretty cool! The intricate circuit pattern might be too fine for a printer tho. I'll print them and let you know how they turn out!

**Comment by CamHardy** [comment]
It looks like there's only one stl in the zip file, and it has a smooth face, unlike any of these renders. What about that circular one (renders 2-6)?
