### ISSUE TITLE
coingecko texts

### ISSUE THREAD

**Issue by bd-ongithub** [turtlecoin/brand#3]
--About
Turtlecoin (TRTL) is a community-focused, constantly evolving  cryptocurrency which follows three simple tenets: Fast, Easy, Safe.
Fast
With blocks being created every 30 seconds on the Turtlecoin blockchain and transactions taking just seconds, sending and paying with TRTL is a breeze.
Easy
Having an extremely active development team and a lively, helpful community, you can start using TRTL in minutes, no matter your familiarity and/or expertise with cryptocurrencies in general.
Mining TRTL is also very easy to get into with simple, detailed how-to guides.
Safe
With its beginnings as a fork of Bytecoin, Turtlecoin offers the same degree of privacy and anonimity with its use of ring-signatures. Just like using paper cash, paying with TRTL allows you to spend your money the way you want.
Being completely open source, the TurtleCoin project is growing daily. We actively encourage the community to jump in with fresh ideas, no matter your skillset or level of experience. Just hop into the discord and say hello! Check out the discord through our link: chat.turtlecoin.lol
    -- Genesis Date
        09/12/2017 Genesis block: https://turtle-coin.com/?hash=8c9738f961a278486f27ce214d1e4d67e08f7400c8b38fe00cdd571a8d302c7d#blockchain_block
    -- Hashing Algorithm
        CryptoNote
    -- Hashrate
        hashrate
    -- Block Time
        30 Seconds
    -- Avialable/Total Supply
        supply/1,000,000,000,000.00 (final supply etc. by year 2150)
- Trading Exchanges
    -- TradeSatoshi.com
    -- TradeOgre.com
- Community
    -- Reddit
        https://www.reddit.com/r/TRTL/
    -- Twitter
        https://twitter.com/_turtlecoin
    -- Facebook
        https://www.facebook.com/trtlcoin
- Developer
    -- Code Repository
        https://github.com/turtlecoin/turtlecoin

**Comment by RocksteadyTC** [comment]
Looks good, I made one correction and changed RingCT Signatures to Ring Signatures. We use ring Signatures.

**Comment by bd-ongithub** [comment]
Oh ok cool, thanks for the clarification, will keep it in mind for the future!

**Comment by RocksteadyTC** [comment]
Great :) You may submit this if you like and reference this comment as permission if needed.

**Comment by RocksteadyTC** [comment]
If not, or if it is not convenient, let me know and I can submit the changes.

**Comment by bd-ongithub** [comment]
If it's possible might be smoother if you can do it, I'm currently not at my usual pc and haven't dealt with coingecko before.

**Comment by RocksteadyTC** [comment]
Sure no problem.
