### ISSUE TITLE
TurtleCoin_Brand_Manual.pdf - Typos and corrections

### ISSUE THREAD

**Issue by derp-derp-derp** [turtlecoin/brand#5]
Debatable, but "COLOURS" should probably be "COLORS" since TurtleCoin was founded in the USA.

"core Identity", I think it should be a lower case i in "identity".

"It’s usage is" should be "Its", with no apostrophe.

**Comment by derp-derp-derp** [comment]
The "colours" => "colors" feedback actually applies to many pages in the document.

**Comment by RocksteadyTC** [comment]
Also there are a few typos, like "it's" vs "its".

**Comment by RocksteadyTC** [comment]
The word "token" should not be used in our materials.
